### ISSUE TITLE
v7.3 merges individual json log records together resulting in a string intermittently. v5.3 works as expected. AWS/EKS hosted application to splunk

### ISSUE THREAD

**Issue by stmiller14** [logfellow/logstash-logback-encoder#1002]
**Describe the bug**
Intermittent issue where aws application write logs to splunk in json format. Logs are getting sent and incorrect format however intermittent issue occurs where logs will be merged into one splunk record and lose its json structre. Happens between 5-10% of logs with no pattern detected 
**To Reproduce**
1. Use this `logback.xml` configuration...
2. Execute this logger statement (e.g. `logger.debug(...)`) ...
3. See error, or unexpected output
host application in aws within eks. write json logs to splunk

**Expected behavior**
json logs records should not be merged together. 

* what output did you expect

**Additional context**

* logstash-logback-encoder version 7.3
* logback version 1.3.5
* jackson version 2.14.2
* java version 17

**Comment by philsttr** [comment]
Please provide your logback configuration
