### ISSUE TITLE
Major version when dropping support for Logback version

### ISSUE THREAD

**Issue by driverpt** [logfellow/logstash-logback-encoder#1006]
**Describe the bug**
We've noticed that you dropped Support for Logback 1.2 in version 7.4 .

This caused our Dependency Update Bot to propose change for 7.4 (Minor version). Can you make this a 8.0 instead of 7.4 instead?

Thanks

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
Spring Boot 2.7

**Comment by philsttr** [comment]
Unfortunately, I cannot un-release something.  In the future I'll bump the major version when dropping support for logback versions
