### ISSUE TITLE
Support for jackson-databind 2.16.x

### ISSUE THREAD

**Issue by jonathannaguin** [logfellow/logstash-logback-encoder#1010]
Hello,

I noticed the library still depends on jackson-databind 2.15.2, however there ir a new version for jackson-databind 2.16.x and can't see an dependecy PR for this.

Is there a compatibility problem that would prevent logstash-logback-encoder to use it?

**Comment by philsttr** [comment]
I have not tried it yet.  Feel free to give it a shot and report any problems you find.
