### ISSUE TITLE
Dependabot errors (cannot maintain this repository)

### ISSUE THREAD

**Issue by jesperronn** [logfellow/logstash-logback-encoder#1020]
The most recent Dependabot PR I could find was https://github.com/logfellow/logstash-logback-encoder/pull/1003

dating back to january, 6 months ago.

From that PR it seems that some of the build jobs cannot run. 

Do we have a maintainer around that can take a look and perhaps trigger a build in the project?

Also perhaps take a look at the dependabot configuration, as it might need some help to start running.

Thanks in advance 👍 . I know maintaining an open source project is not easy and requires unpaid work. 

Please let us know if there is anything the users can help in order to ensure this project is being maintained and updated

**Comment by philsttr** [comment]
dependabot is working now
