### ISSUE TITLE
Faster JSON encoding

### ISSUE THREAD

**Issue by reneleonhardt** [logfellow/logstash-logback-encoder#1026]
**Is your feature request related to a problem? Please describe.**
Are there official benchmarks / performance tests?
For applications with millions of logs per day, JSON encoding speed and garbage collection pauses becomes relevant.

**Describe the solution you'd like**
Automated performance tests should be part of official releases to make regressions visible.
It should compare the throughput for different data formats like CBOR and [Smile](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#non-compatible-easy-smile-binary-json) and using Afterburner.

**Describe alternatives you've considered**
Most people don't use all Jackson features, so for example https://github.com/alibaba/fastjson2 could be a much faster alternative for them.

**Additional context**
https://github.com/alibaba/fastjson2/wiki/fastjson_benchmark

**Comment by philsttr** [comment]
Regarding support for non-jackson serializers, see [this answer](https://github.com/logfellow/logstash-logback-encoder/discussions/984#discussioncomment-6853318).

There are no official benchmarks or performance tests or plans to develop them.   I don't have the time or resources to maintain them.  If you notice specific performance problems, please file issues with a reproducible scenario.
