### ISSUE TITLE
tryJson drops logs when JSON object has a field with null value

### ISSUE THREAD

**Issue by nbardiuk** [logfellow/logstash-logback-encoder#702]
**Describe the bug**
`tryJson` drops logs when JSON object has a field with a null value

**To Reproduce**
1. Use this `logback.xml` configuration...
```xml
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>
            {
              "event":"#tryJson{%message}"
            }
          </pattern></pattern>
            </providers>
        </encoder>
    </appender>

```
2. Execute this logger statement 
```java
logger.debug("{\"field\":null}");
```
3. See error, or unexpected output
the log is empty

**Expected behavior**
The log output should contain
```json
"event":{"field":null}
```

**Additional context**
This used to work with logstash-logback-encoder 6.6

* logstash-logback-encoder 7.0
* logback version 1.2.7
* jackson version 2.13.0
* java version OpenJDK 64-Bit Server VM 11.0.11+9

**Comment by brenuart** [comment]
Hi @nbardiuk ,

Thanks for the report. I can confirm this is a bug (a regression) introduced in 7.0
If you register a status listener and print logback statuses on the console (see [here)](http://logback.qos.ch/manual/configuration.html#dumpingStatusData) you will notice an exception is thrown while trying to serialise the JSON object. The problem occurs when trying to serialise a complex JsonNode (Object, Map or Array) with one its children elements being null.

I'm sorry but there is no workaround for this issue. We are working on it. Stay tuned...

PS: how urgent is it for you to solve this issue? Are you just giving 7.0 a try or do you want to roll it into production?

**Comment by nbardiuk** [comment]
We tried to use the new version and have noticed the issue.
As a workaround, we can use the previous version, which works great for us. 
Thank you for looking into it.
