### ISSUE TITLE
ObjectAppendingMarker in v7.0+ has no means to access the fieldValue as its object type

### ISSUE THREAD

**Issue by timorjim** [logfellow/logstash-logback-encoder#719]
**Describe the bug**
Have a test using AssertJ that accesses the field in ObjectAppendingMarker. It previously was called `object` and the test could access it as the correct object type. v7.0 renamed the field to be `fieldValue` and the AssertJ reflection favours the `getFieldValue` method over the field itself, and the getter always returns a string.

Is there a way to get the fieldValue as its type rather than a string? I have a value that is a map, and having this converted to a string makes testing problematic.

**Comment by brenuart** [comment]
@tim: is the proposed PR ok for you ?

**Comment by timorjim** [comment]
@brenuart that sounds good to me. Appreciate the quick response! Thanks
