### ISSUE TITLE
Enable simple class name in logger name customization

### ISSUE THREAD

**Issue by twessendorf** [logfellow/logstash-logback-encoder#747]
**Is your feature request related to a problem? Please describe.**
I didn't succeed in shortening the logger name to simple class name. [Although it is stated](https://github.com/logfellow/logstash-logback-encoder#customizing-logger-name-length) that `shortenedLoggerNameLength` behaves similar to normal pattern style,  `<shortenedLoggerNameLength>0</shortenedLoggerNameLength>` doesn't result in simple class name as `%logger{0}` does. In fact, `foo.bar.baz.MyClass` is shortened to `f.b.b.MyClass` instead of `MyClass`.

**Describe the solution you'd like**
I'd like `shortenedLoggerNameLength` to behave the same way as normal pattern style for `0` parameter to enable simple class name logger customization.

**Comment by brenuart** [comment]
Hi @twessendorf ,

First of all, sorry for the late answer :-(
Secondly, there is indeed a problem with how the logger name is shortened when the length is set to `0` (as you noticed). It works however as expected when the length is greater than zero.

As a workaround you can make use of the [PatternJsonProvider](https://github.com/logfellow/logstash-logback-encoder#pattern-json-provider) as shown below:

```
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
    <providers>
        <pattern>
            <pattern>
                { "logger": "%logger{0}" }
            </pattern>
        </pattern>
    </providers>
</encoder>
```

Note that you cannot rely on the LogstashEncoder and you will have to redefine all the required JsonProviders manually...
