### ISSUE TITLE
Structured fields are no longer printed when using log4j 2.17.1

### ISSUE THREAD

**Issue by frankjkelly** [logfellow/logstash-logback-encoder#754]
**Describe the bug**
NOTE: Cross-posting from here
https://stackoverflow.com/questions/70960924/logstash-writing-logs-as-json-but-structured-arguments-are-missing

When we upgraded our Spring to use log4j 2.17.1 the structured logs no longer contained any structured fields we added to the log statement.

I am logging several structured arguments as follows 
```
        log.info("Get container",
                v(StructuredLoggingFields.TENANT_ID, tenantId),
                v(StructuredLoggingFields.CONTAINER_ID, containerId));
```
NOTE: That class is instrumented with@Log4j2

but not seeing the arguments in the JSON in the log file
```
{
  "app":"Signal Service",
  "ts":"2022-02-02T18:22:21.312Z",
  "level":"INFO",
  "class":"com.tbd.platform.signal.controller.ContainerController",
  "method":"getContainer",
  "caller_file_name":"ContainerController.java",
  "line":153,"thread":"http-nio-8080-exec-2", 
  "msg":"Get container"
}
```

**To Reproduce**
1. Use this `logback-spring.xml` config below (although it's not critical to the issue I think)
2. Use spring 2.5.9 or 2.6.3 with log4j e.g. lombok `@Log4j2` https://projectlombok.org/features/log
3. Log a message with extra structured arguments

**Expected behavior**
Expected extra structured arguments to be printed to console.

NOTE: If you switch to `@Slf4j` they get printed fine so my guess is it's something to do with the change in log4j to 2.17.1 (as it worked with Spring 2.5.8 with log4j 2.17.0 but not Spring 2.5.9 with log4j 2.17.1)

Let me know if you need anything else. Thanks!

**Additional context**

* logstash-logback-encoder 7.0.1
* logback 1.2.6
* jackson 2.12.5
* java 11

logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <contextName>Signal Service</contextName>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <contextName>
                    <fieldName>app</fieldName>
                </contextName>
                <timestamp>
                    <fieldName>ts</fieldName>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <logLevel>
                    <fieldName>level</fieldName>
                </logLevel>
                <callerData>
                    <classFieldName>class</classFieldName>
                    <methodFieldName>method</methodFieldName>
                    <lineFieldName>line</lineFieldName>
                </callerData>
                <threadName>
                    <fieldName>thread</fieldName>
                </threadName>
                <mdc/>
                <arguments>
                    <includeNonStructuredArguments>false</includeNonStructuredArguments>
                </arguments>
                <stackTrace>
                    <fieldName>stack</fieldName>
                </stackTrace>
                <message>
                    <fieldName>msg</fieldName>
                </message>
            </providers>
        </encoder>
    </appender>
    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
```

**Comment by brenuart** [comment]
Sorry but I don't fully understand your setup :-(
It seems you are mixing both Logback and Log4J2 - that means two distinct logger implementation.

You say that "it doesn't work" when your class is instrumented with `@Log4J2` but works as expected when it is instead annotated with `@Slf4j`.
The `@Log4j2` Lombok annotation creates a "plain" Log4J2 logger meaning that log statements are handled by Log4J2 and Logback is not involved at all. StructuredArguments are logstash-logback-encoder stuff and are not designed to work with logger implementations other than Logback.
The '@Slf4J' annotation creates an SLF4J logger backed with the concrete implementation the SLF4J bootstrap has found. Since you say it works as expected when switching to SLF4J - it probably means that Logback is the concrete logger implementation behind the SLF4J facade.

Tell me if it missed something in your setup...
Also, I would not recommend using both Log4J2 AND Logback at the same time. Choose one implementation (logback since you are using this project) and write your code to log against the SLF4J facade.

**Comment by frankjkelly** [comment]
@brenuart Thanks for the reply - yeah given what you said I am not sure how `@Log4j2` annotation ever fully worked unless there was some bridging going on to Slf4j perhaps. And then the question becomes why did it break when log4j changed?

Beyond using the lombok plugin and forcing the log4j variant (needed for other implementation dependencies that require log4j)
```
ext['log4j2.version'] = '2.17.1'
```
I don't see us doing anything else "log-wise".

But I agree with your diagnosis that we should just use `@Slf4j` and logback.

**Comment by philsttr** [comment]
In these cases, usually the [Log4j 2 to SLF4J Adapter](https://logging.apache.org/log4j/log4j-2.2/log4j-to-slf4j/index.html) is used to redirect code that uses the log4j2 APIs to slf4j, which then delegates to logback.  So, in theory this should still work.

Please make sure you are using log4j-to-slf4j to redirect log4j2 APIs to slf4j AND NOT using log4j-slf4j-impl

**Comment by brenuart** [comment]
Why do you need both Logback AND Log4J2 at the same time?

**Comment by frankjkelly** [comment]
@brenuart We don't - it was just we decided to use `@Log4j2` and it just worked and we stayed consistent with that decision. It hasn't been an issue until now. Thanks!

**Comment by brenuart** [comment]
Ok, so:
- remove Log4J2 from your dependencies
- add a dependency on Slf4J
- use @Slf4J (optional)
- use Logback and logstash-Logback-encoder 

... and you are all set ;-)

**Comment by frankjkelly** [comment]
🥇

**Comment by brenuart** [comment]
(Can we close this issue?)

**Comment by frankjkelly** [comment]
Sounds good - please do
