### ISSUE TITLE
Update license header template for 2022

### ISSUE THREAD

**Issue by brenuart** [logfellow/logstash-logback-encoder#766]
The license template expects the copyright year to be 2021 - it should be updated to expect **2022** instead.

**Comment by brenuart** [comment]
Also check why the license header is specified in two places:
- once in the license plugin (ok)
- a second time in the checkstyle configuration (why?)

**Comment by brenuart** [comment]
@philsttr Do you remember any reason why the license header is also enforced by checkstyle in addition to the license maven plugin? It looks like a left over from before we introduced the license plugin and relied solely on checkstyle...

**Comment by philsttr** [comment]
I believe it is a leftover.

**Comment by philsttr** [comment]
I'm not a lawyer, but I believe they are still protected as long as they aren't changed.  I think technically the year only needs to be updated if they are changed.  But we can mass-update them if it helps our automation.
