### ISSUE TITLE
Provide Annotation Based Field Masker

### ISSUE THREAD

**Issue by frank-kiwi** [logfellow/logstash-logback-encoder#779]
The FieldNameBasedFieldMasker is great to have and makes masking fields really easy.  Unfortunately, it is really difficult to configure and maintain for a big object model.

It would be great to be able to annotate the fields in the object model and have them automatically masked in the output.

**Comment by philsttr** [comment]
See https://github.com/logfellow/logstash-logback-encoder/pull/782#issuecomment-1086726551
