### ISSUE TITLE
logging uuid in LoggingEventCompositeJsonEncoder custom pattern 

### ISSUE THREAD

**Issue by pkm2022** [logfellow/logstash-logback-encoder#821]
Hello,   How can I include uuid inside a pattern (see below).  This "uuid" : "%uuid" does not work but \<uuid \/> works.   	

   <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
			<providers>
				<pattern>
					<pattern>
						{
						"application" : "myapp",
						"timestamp": "%date{yyyy-MM-dd'T'HH:mm:ss.SSSX, UTC}",
						"logger": "%logger",
						"level": "%level",
						"message": "%message",
						"thread" : "%thread",
						"line" : "%line",
						"uuid" : "%uuid"
						}
					</pattern>
					
				</pattern>
				<uuid />
			</providers>
		</encoder>
	</appender>

I am using below in pom.xml

		
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>7.2</version>
		</dependency>

		
		<dependency>
			<groupId>com.fasterxml.uuid</groupId>
			<artifactId>java-uuid-generator</artifactId>
			<version>4.0.1</version>
		</dependency>

**Comment by brenuart** [comment]
Hello,

As mentioned in the documentation, the `PatternJsonProvider` takes a standard logback _pattern layout_ as argument. For that reason only the standard logback _conversion specifiers_ can be used - reason why `%uuid` is not supported.

Luckily Logback allows you to write your own custom conversion specifier as described in https://logback.qos.ch/manual/layouts.html#customConversionSpecifier. The process is well described and quite easy to implement. No doubt you'll be able to enhance the standard layout to provide support for `%uuid` backed by an id generation strategy of your choice.

Feel free to come back here for more info if needed.
