### ISSUE TITLE
How to add a custom AppenderListener

### ISSUE THREAD

**Issue by ptko5** [logfellow/logstash-logback-encoder#828]
net.logstash.logback.appender.LogstashTcpSocketAppender
Want to add a custom TcpAppenderListener

**Comment by brenuart** [comment]
Check [Appender Listeners](https://github.com/logfellow/logstash-logback-encoder#appender-listeners)... Does it answer your question? If not, feel free to provide more details about what you are trying to do.

**Comment by ptko5** [comment]
Thanks
