### ISSUE TITLE
Value Masking: adding multiple values in a single <values> entry makes the implicit assumption that the values to match does not contain a comma

### ISSUE THREAD

**Issue by brenuart** [logfellow/logstash-logback-encoder#847]
Adding multiple values using a single `<values>` entry as described in https://github.com/logfellow/logstash-logback-encoder#identifying-field-values-to-mask-by-value makes the implicit assumption that the values to match do not contain a comma. 

Considering that the alternative is to use multiple distinct `<value>` entries, I propose to deprecate the `<values>` configuration parameter to avoid any confusion or risk of unwanted "bad" configuration from the user.

Of course we should first deprecate the option and schedule it for removal for the next major release.

**Comment by philsttr** [comment]
I intended `values` to allow setting multiple values from a property, which would allow maintaining those values outside of logback xml.

As an alternative, we could investigate allowing escaping of commas for anyone that wanted to include a comma as part of a string to mask.   Or, just leave as is, document the behavior, and use `value` for anything that needs a comma.
