### ISSUE TITLE
DestinationParser does not accept IPV6 addresses

### ISSUE THREAD

**Issue by aa122121** [logfellow/logstash-logback-encoder#848]
**IPv6 environment is not supported**
When I try to configure the IPv6 address, I find an error：“No destination was configured. Use to add one or more destinations to the appender”.
I checked the source code and found that the regular expression when getting host only supports IPv4

source code location：/src/main/java/net/logstash/logback/appender/destination/DestinationParser.java
screenshot：
![image](https://user-images.githubusercontent.com/9084490/187421495-08ffa5c7-db97-4e6b-9cc6-a0b8b43c20c7.png)
![image](https://user-images.githubusercontent.com/9084490/187421612-c60721cd-ea47-4fca-8d4a-12c11fcefdb6.png)

**Comment by brenuart** [comment]
Nice catch!
Looks like you are one of the first using IPv6 addresses ;-)

I'll have a look asap. Stay tuned.

(how urgent is it for you?)

**Comment by brenuart** [comment]
@philsttr What's your opinion?

**Comment by aa122121** [comment]
> Nice catch! Looks like you are one of the first using IPv6 addresses ;-)
> 
> What text format would you expect? Something like this:
> 
> ```
> [2001:db8::1]:8080
> ```
> 
> This format is typically used in URL and is easy to parse: address is simply enclosed within brackets. RFC 5952 proposes a few other alternatives but they are unfortunately more complex to parse.
> 
> I'll have a look asap. Stay tuned.
> 
> (how urgent is it for you?)
I use the typical format：  ```[2001:db8::1]:8080``` .
The project I participated in needs to adapt to IPv6 as soon as possible. Consequently, it's a very urgent problem for me

**Comment by brenuart** [comment]
@aa122121 That should work now. We are planning a new release in the next couple of days. In the meantime feel free to build the project yourself and give it a try..

**Comment by aa122121** [comment]
@brenuart ok
