### ISSUE TITLE
Ignoring unknown property [encoder] in [net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender]

### ISSUE THREAD

**Issue by tony-schellenberg** [logfellow/logstash-logback-encoder#870]
Hello, I'm having some struggles upgrading libraries in a project we have and would appreciate any help or insights you might have.

**Describe the bug**
I have an existing project that I'm trying to upgrade some library versions on. When I upgrade them, I'm not able to get my log output from the JSON configured logger. Here are what I believe are the relevant version changes:
* logback 1.2.11 -> 1.4.3
* slf4j 1.7.36 -> 2.0.3
* logstash-logback-encoder 7.2

My configuration stanza is:
```
    <appender name="jsonConsoleAppender" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                <providers>
                    <logLevel/>
                    <message/>
                    <arguments/>
                    <logstashMarkers/>
                    <mdc/>
                    <threadName/>
                    <loggerName/>
                    <tags/>
                    <rootStackTraceElement/>
                    <stackTrace/> <!-- Interesting problem with code folding in intellij https://www.jetbrains.com/help/idea/settings-console-folding.html -->
                </providers>
            </encoder>
        </appender>
    </appender>
```

I added the debug flag to the logback config and I get this output with a plain stdout logger:
```
09:46:05,928 |-INFO in ch.qos.logback.classic.model.processor.LoggerContextListenerModelHandler - Starting LoggerContextListener                                                                           
09:46:05,931 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
09:46:05,931 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:46:05,944 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property                       
09:46:05,957 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [jsonConsoleAppender]
09:46:05,958 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender]
09:46:05,962 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [encoder] in [net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender]
```

**Expected behavior**
With the previous versions, my log lines show up JSON encoded nicely. With the updated versions, there's no logging output from the configured stanza

**Additional context**
If I configure just a plain console appender, I get the logging that I expect (not JSON formatter though). Also, rolling back the versions noted at the top corrects the logging too. So, it seems like the logging is working but it's failing to load this configuration with the updated versions?

* logstash-logback-encoder version 7.2
* logback version 2.0.3
* jackson version 2.13.4
* java version 11.0.16

**Comment by brenuart** [comment]
Hi @tony-schellenberg,

I think this is caused by https://jira.qos.ch/browse/LOGBACK-1674... According to the issue description you should declare the console appender outside of the async appender instead of nesting them, then use `<appender-ref>` to refer to it...

It is not clear to me if this behaviour is intended or not and if the former construction is now obsolete and should be avoided. 

Tell me if it works ok with this change...

**Comment by tony-schellenberg** [comment]
@brenuart Thank you so much! I really appreciate the help and that looks like it solved my problems.
