### ISSUE TITLE
ShortenedThrowableConverter: <exclude> and <exclusions> are mutually exclusive

### ISSUE THREAD

**Issue by brenuart** [logfellow/logstash-logback-encoder#876]
Suppose the following configuration:

```xml
<throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
    <exclude>pattern1</exclude>
    <exclusions>${STACK_EXCLUSIONS}</exclusions>
    <exclude>pattern2</exclude>
</throwableConverter>
```

Using the `<exclusions>` with an environment variable is an easy way to configure additional exclusion patterns in addition to those already configured in the XML file. However, it happens that `<exclusions>` clears the exclusions already configured and replace them with new values. This sample configuration results in only TWO exclusion patterns with the first one being ignored... 

To avoid confusion the `<exclusions>` keyword should ADD new patterns instead of replacing those already defined.

**Comment by brenuart** [comment]
@philsttr What do you think of this?

**Comment by philsttr** [comment]
Sounds good.  

I think there is a low probability that anyone is using both.
