### ISSUE TITLE
Missing Logstash server causes a crash

### ISSUE THREAD

**Issue by kenwdelong** [logfellow/logstash-logback-encoder#910]
**Describe the bug**
When the Logstash server goes down, the encoder can have threads that get stuck holding synchronization locks that end up blocking other threads that are trying to call the logging system.

When the logstash server is not available, I see an immediate degradation in my application process's health: response times skyrocket, and the number of open files skyrocket.

A thread dump shows all but one of the HTTP handling threads (which are calling the logback logger) are stuck waiting on a synchronization lock held by the one:

```
sun.nio.ch.DatagramChannelImpl.send0(): -2
sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(): 901
sun.nio.ch.DatagramChannelImpl.send(): 863
sun.nio.ch.DatagramChannelImpl.send(): 821
sun.nio.ch.DatagramChannelImpl.blockingSend(): 853
sun.nio.ch.DatagramSocketAdaptor.send(): 218
java.net.DatagramSocket.send(): 669
ch.qos.logback.core.net.SyslogOutputStream.flush(): 69
net.logstash.logback.appender.AbstractLogstashUdpSocketAppender.append(): 96
net.logstash.logback.appender.AbstractLogstashUdpSocketAppender.append(): 35
ch.qos.logback.core.AppenderBase.doAppend(): 82
ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(): 51
ch.qos.logback.classic.Logger.appendLoopOnAppenders(): 270
ch.qos.logback.classic.Logger.callAppenders(): 257
ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(): 421
ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(): 383
ch.qos.logback.classic.Logger.info(): 579

```
Every other thread reports waiting on the lock held by this thread on line 82 of AppenderBase.doAppend().  Apparently because the remote Logstash server is not available, this method is taking extra long (seconds?) and the other threads pile up waiting for this lock.

**To Reproduce**
1. Using this config
```
	<appender name="stash" class="net.logstash.logback.appender.LogstashUdpSocketAppender">
		<host>elk.myco.corp</host>
		<port>5001</port>
		<layout class="net.logstash.logback.layout.LogstashLayout"/>
	</appender>

```
2. The application process calling the logger is logging about 100-200 messages/second
3. With scan=true in logback.xml, edit the config to replace the hostname in the appender with an address that does not resolve to any server. OR, simply take the Logstash server offline.

**Expected behavior**
The appender should either not lock, or guarantee a quick return if the remote Logstash process is not available.

**Additional context**

I am operating in an AWS VPC with two subnets, A and B.  The application process calling the logger is in subnet A.  If I change the config to point at an "empty" IP in subnet A, I get this bad behavior.  Bizzarely, if I point the appender host to an IP address in the other subnet (B), no bad behavior is observed. For some reason, the "broken" network calls are failing fast when the destination is in a different subnet, but hanging when in the same subnet.

* logstash-logback-encoder version 7.2
* logback version 1.2.11
* jackson version 2.13.4
* java version  17.0.5

**Comment by kenwdelong** [comment]
Oh dear.  Now that I have RTFMC (Read The Fine Manual _Carefully_) I realize that although the TCP appenders are async, the UDP appenders are not, and I need additional config to wrap them in an AsyncAppender wrapper.  So this was all my fault.

**Comment by brenuart** [comment]
Yes, you are correct, the UDP appender is unfortunately not (yet) async.
However, I'm quite surprised to sending a UDP datagram may block the thread as you are describing. Is it the same when you start sending to a destination without any listener? Or does it happen only when the receiving side dies after some packets have already been sent?

**Comment by kenwdelong** [comment]
I was also shocked to see that. I thought perhaps I've uncovered some subtle Java 17 bug?  It was reproducible that only the servers in the same subnet exhibited the problems, which makes no sense at all.

I tried to write a little script to mimic what `SyslogOutputStream` is doing:

```
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;

public class Scrap
{

	public static void main(String[] args) throws Exception
	{
            var address = InetAddress.getByName("10.0.2.86");
            int port = 5001;
            DatagramSocket ds = new DatagramSocket();
        
            for(int i = 0; i < 10; i++)
            {
	        byte[] bytes = "this is a message".getBytes();
	        long start = System.nanoTime();
	        DatagramPacket packet = new DatagramPacket(bytes, bytes.length, address, port);
	        ds.send(packet);
	        long stop = System.nanoTime();
	        long elapsed = stop - start;
	        System.out.println("Network call took " + 1.0*elapsed/1_000_000 + " ms");
            }

            ds.close();
	}

}
```


However, the operation completes in under a millisecond (generally under 100 microseconds) no matter the network configuration (same subnet or different subnet, IP address or hostname).

In any event, I learned that logback's appenders are also not async by default.  So I've wrapped just about everything in `LoggingEventAsynDisruptorAppender` which, just by the awesomeness of it's name, should prevent this from happening again!
